BEGIN {
    FS="\t"
    print("// This file is automatically generated by Resources/table.awk")
   
}
/^#/{
    printf("// %s\n", $1);
    next;
}
{
    if(!table){
        printf("\n\nchar %s[] {\n", TABLENAME)
        printf("//   out         in  comment\n");
        table =1;
    }
    printf("    %s, // %s %s\n", $2,$1,$3)
}
END {
    print("};");
}
