#
# Print out in property list xml format some interesting environment variables

    
BEGIN {
    FS="|"
    printf("  <!-- Generated by interesting_environments.awk -->\n");
    printf("  <key>Environment</key>\n");
    printf("    <dict>\n");
           
}

{
    sub(/=/,"|", $0);
    if($1 ~ /^GCC*/ || $1 ~ /^CLANG*/){
        gsub(/"/,"&quot;",$2)
        printf("      <key>%s</key>\n",$1);
        printf("        <string>%s</string>\n",$2);
    }
}
END {
    printf("    </dict>\n")
}
