BEGIN {
	printf "<h1>Release and Install notes</h1>\n\n"
	}
	


END    {
	printf "\n\nAutomatically generated by makereleaseindex.awk\n"
	}

	{
	printf "<h1>Version %s</h1>\n", $1
	printf "[/doc/RELEASE-%s/NOTES/RELEASE.html|Release notes]<br>\n", $1
	printf "[/doc/RELEASE-%s/NOTES/INSTALL.html|Install notes]\n", $1
	printf "\n\n"
	}

