# This script is sourced by version-script.sh
# Generate a plist containing info about Vole for the 
# Check-For-Updates facility

filename=VoleInfo.plist

echo vscript-xml.sh started
echo Filename is ${filename}

function nolf(){
   tr -d '\012'
}


cat >${filename} <<EOF1
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<!-- This file is automatically generated by vscript-xml.sh.
     Do not edit. Do not check into Fossil or Git. -->
<dict>
  <key>ProductName</key>
    <string>${PRODUCT_NAME}</string>
  <key>Version</key>
    <string>$(marketing_version | nolf)</string>
  <key>BuildDate</key>
    <string>${builddate}</string>
  <key>BuildUUID</key>
    <string>${build_uuid}</string>
  <key>BuildID</key>
    <string>${BUILDID}</string>
  <key>Configuration</key>
    <string>${CONFIGURATION}</string>
  <key>ProjectFilePath</key>
    <string>${PROJECT_FILE_PATH}</string>
</dict>
</plist>
EOF1

exit 0
