# This script is sourced by version-script.sh.
# It should not be run independently.
# Generate a plist containing info about Vole for the 
#   Check-For-Updates facility.

filename=VoleInfo.plist

echo vscript-xml.sh started
echo Filename is ${filename}

function nolf(){
# delete linefeeds from stdin
   tr -d '\012'
}

function archs_array(){
# Generate a array of Archs
printf "  <key>Archs</key>\n"
printf "    <array>\n"
for i in "${ARCHS}"
do
printf "      <string>%s</string>\n" ${i}
done
printf "    </array>\n"
}

function iso_date(){
# print date in ISO 8601 format (see plist dtd for acceptable format)
TZ=UTC date +%Y-%m-%dT%H:%M:%SZ
}

cat >${filename} <<EOF1
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<!-- This file is automatically generated by vscript-xml.sh.
     Do not edit. Do not check into Fossil or Git.
     This file is placed in the Resources folder of the App -->
<!-- ** This file cannot be edited by Xcode's Property List editor,
     ** it does not like the <date> element, and generally gets confused -->
<dict>
  <key>ProductName</key>
    <string>${PRODUCT_NAME}</string>
  <key>Version</key>
    <string>$(marketing_version | nolf)</string>
  <key>MaxOSXVersion</key>
    <string>Not Implemented yet</string>
  <key>BuildDate</key>
    <string>${builddate}</string>
  <key>BuildDateISO</key>
    <date>$(iso_date | nolf)</date>
  <key>BuildUUID</key>
    <string>${build_uuid}</string>
  <key>BuildID</key>
    <string>${BUILDID}</string>
  <key>Configuration</key>
    <string>${CONFIGURATION}</string>
  <key>ProjectFilePath</key>
    <string>${PROJECT_FILE_PATH}</string>
  <key>DeploymentTarget</key>
    <string>${MACOSX_DEPLOYMENT_TARGET}</string>
  <key>SDKName</key>
    <string>${SDK_NAME}</string>
  <key>VCSStatus</key>
    <string>${VCSSTATUS}</string>
  <key>VCSDate</key>
    <string>${VCSDATE}</string>
  <key>VCSUncheckedFiles</key>
    <integer>$(printf "%d" ${unchecked_files})</integer>
  <key>VCSCheckin</key>
    <string>$(uuid_checkin | nolf)</string>   
$(archs_array)
</dict>
</plist>
EOF1

exit 0
