/* This file is automatically generated by cp1252table-gen
   ===================== Do Not Edit ===================== */
/* This is a lookup table to convert from cp1252 to utf-8 */

struct { char *utf8bytes; int nbytes; } codetable[] = { 
{ "\x00",1 },	/* 00  0000 #NULL */
{ "\x01",1 },	/* 01  0001 #START OF HEADING */
{ "\x02",1 },	/* 02  0002 #START OF TEXT */
{ "\x03",1 },	/* 03  0003 #END OF TEXT */
{ "\x04",1 },	/* 04  0004 #END OF TRANSMISSION */
{ "\x05",1 },	/* 05  0005 #ENQUIRY */
{ "\x06",1 },	/* 06  0006 #ACKNOWLEDGE */
{ "\x07",1 },	/* 07  0007 #BELL */
{ "\x08",1 },	/* 08  0008 #BACKSPACE */
{ "\x09",1 },	/* 09  0009 #HORIZONTAL TABULATION */
{ "\x0a",1 },	/* 0A  000A #LINE FEED */
{ "\x0b",1 },	/* 0B  000B #VERTICAL TABULATION */
{ "\x0c",1 },	/* 0C  000C #FORM FEED */
{ "\x0d",1 },	/* 0D  000D #CARRIAGE RETURN */
{ "\x0e",1 },	/* 0E  000E #SHIFT OUT */
{ "\x0f",1 },	/* 0F  000F #SHIFT IN */
{ "\x10",1 },	/* 10  0010 #DATA LINK ESCAPE */
{ "\x11",1 },	/* 11  0011 #DEVICE CONTROL ONE */
{ "\x12",1 },	/* 12  0012 #DEVICE CONTROL TWO */
{ "\x13",1 },	/* 13  0013 #DEVICE CONTROL THREE */
{ "\x14",1 },	/* 14  0014 #DEVICE CONTROL FOUR */
{ "\x15",1 },	/* 15  0015 #NEGATIVE ACKNOWLEDGE */
{ "\x16",1 },	/* 16  0016 #SYNCHRONOUS IDLE */
{ "\x17",1 },	/* 17  0017 #END OF TRANSMISSION BLOCK */
{ "\x18",1 },	/* 18  0018 #CANCEL */
{ "\x19",1 },	/* 19  0019 #END OF MEDIUM */
{ "\x1a",1 },	/* 1A  001A #SUBSTITUTE */
{ "\x1b",1 },	/* 1B  001B #ESCAPE */
{ "\x1c",1 },	/* 1C  001C #FILE SEPARATOR */
{ "\x1d",1 },	/* 1D  001D #GROUP SEPARATOR */
{ "\x1e",1 },	/* 1E  001E #RECORD SEPARATOR */
{ "\x1f",1 },	/* 1F  001F #UNIT SEPARATOR */
{ "\x20",1 },	/* 20  0020 #SPACE */
{ "\x21",1 },	/* 21  0021 #EXCLAMATION MARK */
{ "\x22",1 },	/* 22  0022 #QUOTATION MARK */
{ "\x23",1 },	/* 23  0023 #NUMBER SIGN */
{ "\x24",1 },	/* 24  0024 #DOLLAR SIGN */
{ "\x25",1 },	/* 25  0025 #PERCENT SIGN */
{ "\x26",1 },	/* 26  0026 #AMPERSAND */
{ "\x27",1 },	/* 27  0027 #APOSTROPHE */
{ "\x28",1 },	/* 28  0028 #LEFT PARENTHESIS */
{ "\x29",1 },	/* 29  0029 #RIGHT PARENTHESIS */
{ "\x2a",1 },	/* 2A  002A #ASTERISK */
{ "\x2b",1 },	/* 2B  002B #PLUS SIGN */
{ "\x2c",1 },	/* 2C  002C #COMMA */
{ "\x2d",1 },	/* 2D  002D #HYPHEN-MINUS */
{ "\x2e",1 },	/* 2E  002E #FULL STOP */
{ "\x2f",1 },	/* 2F  002F #SOLIDUS */
{ "\x30",1 },	/* 30  0030 #DIGIT ZERO */
{ "\x31",1 },	/* 31  0031 #DIGIT ONE */
{ "\x32",1 },	/* 32  0032 #DIGIT TWO */
{ "\x33",1 },	/* 33  0033 #DIGIT THREE */
{ "\x34",1 },	/* 34  0034 #DIGIT FOUR */
{ "\x35",1 },	/* 35  0035 #DIGIT FIVE */
{ "\x36",1 },	/* 36  0036 #DIGIT SIX */
{ "\x37",1 },	/* 37  0037 #DIGIT SEVEN */
{ "\x38",1 },	/* 38  0038 #DIGIT EIGHT */
{ "\x39",1 },	/* 39  0039 #DIGIT NINE */
{ "\x3a",1 },	/* 3A  003A #COLON */
{ "\x3b",1 },	/* 3B  003B #SEMICOLON */
{ "\x3c",1 },	/* 3C  003C #LESS-THAN SIGN */
{ "\x3d",1 },	/* 3D  003D #EQUALS SIGN */
{ "\x3e",1 },	/* 3E  003E #GREATER-THAN SIGN */
{ "\x3f",1 },	/* 3F  003F #QUESTION MARK */
{ "\x40",1 },	/* 40  0040 #COMMERCIAL AT */
{ "\x41",1 },	/* 41  0041 #LATIN CAPITAL LETTER A */
{ "\x42",1 },	/* 42  0042 #LATIN CAPITAL LETTER B */
{ "\x43",1 },	/* 43  0043 #LATIN CAPITAL LETTER C */
{ "\x44",1 },	/* 44  0044 #LATIN CAPITAL LETTER D */
{ "\x45",1 },	/* 45  0045 #LATIN CAPITAL LETTER E */
{ "\x46",1 },	/* 46  0046 #LATIN CAPITAL LETTER F */
{ "\x47",1 },	/* 47  0047 #LATIN CAPITAL LETTER G */
{ "\x48",1 },	/* 48  0048 #LATIN CAPITAL LETTER H */
{ "\x49",1 },	/* 49  0049 #LATIN CAPITAL LETTER I */
{ "\x4a",1 },	/* 4A  004A #LATIN CAPITAL LETTER J */
{ "\x4b",1 },	/* 4B  004B #LATIN CAPITAL LETTER K */
{ "\x4c",1 },	/* 4C  004C #LATIN CAPITAL LETTER L */
{ "\x4d",1 },	/* 4D  004D #LATIN CAPITAL LETTER M */
{ "\x4e",1 },	/* 4E  004E #LATIN CAPITAL LETTER N */
{ "\x4f",1 },	/* 4F  004F #LATIN CAPITAL LETTER O */
{ "\x50",1 },	/* 50  0050 #LATIN CAPITAL LETTER P */
{ "\x51",1 },	/* 51  0051 #LATIN CAPITAL LETTER Q */
{ "\x52",1 },	/* 52  0052 #LATIN CAPITAL LETTER R */
{ "\x53",1 },	/* 53  0053 #LATIN CAPITAL LETTER S */
{ "\x54",1 },	/* 54  0054 #LATIN CAPITAL LETTER T */
{ "\x55",1 },	/* 55  0055 #LATIN CAPITAL LETTER U */
{ "\x56",1 },	/* 56  0056 #LATIN CAPITAL LETTER V */
{ "\x57",1 },	/* 57  0057 #LATIN CAPITAL LETTER W */
{ "\x58",1 },	/* 58  0058 #LATIN CAPITAL LETTER X */
{ "\x59",1 },	/* 59  0059 #LATIN CAPITAL LETTER Y */
{ "\x5a",1 },	/* 5A  005A #LATIN CAPITAL LETTER Z */
{ "\x5b",1 },	/* 5B  005B #LEFT SQUARE BRACKET */
{ "\x5c",1 },	/* 5C  005C #REVERSE SOLIDUS */
{ "\x5d",1 },	/* 5D  005D #RIGHT SQUARE BRACKET */
{ "\x5e",1 },	/* 5E  005E #CIRCUMFLEX ACCENT */
{ "\x5f",1 },	/* 5F  005F #LOW LINE */
{ "\x60",1 },	/* 60  0060 #GRAVE ACCENT */
{ "\x61",1 },	/* 61  0061 #LATIN SMALL LETTER A */
{ "\x62",1 },	/* 62  0062 #LATIN SMALL LETTER B */
{ "\x63",1 },	/* 63  0063 #LATIN SMALL LETTER C */
{ "\x64",1 },	/* 64  0064 #LATIN SMALL LETTER D */
{ "\x65",1 },	/* 65  0065 #LATIN SMALL LETTER E */
{ "\x66",1 },	/* 66  0066 #LATIN SMALL LETTER F */
{ "\x67",1 },	/* 67  0067 #LATIN SMALL LETTER G */
{ "\x68",1 },	/* 68  0068 #LATIN SMALL LETTER H */
{ "\x69",1 },	/* 69  0069 #LATIN SMALL LETTER I */
{ "\x6a",1 },	/* 6A  006A #LATIN SMALL LETTER J */
{ "\x6b",1 },	/* 6B  006B #LATIN SMALL LETTER K */
{ "\x6c",1 },	/* 6C  006C #LATIN SMALL LETTER L */
{ "\x6d",1 },	/* 6D  006D #LATIN SMALL LETTER M */
{ "\x6e",1 },	/* 6E  006E #LATIN SMALL LETTER N */
{ "\x6f",1 },	/* 6F  006F #LATIN SMALL LETTER O */
{ "\x70",1 },	/* 70  0070 #LATIN SMALL LETTER P */
{ "\x71",1 },	/* 71  0071 #LATIN SMALL LETTER Q */
{ "\x72",1 },	/* 72  0072 #LATIN SMALL LETTER R */
{ "\x73",1 },	/* 73  0073 #LATIN SMALL LETTER S */
{ "\x74",1 },	/* 74  0074 #LATIN SMALL LETTER T */
{ "\x75",1 },	/* 75  0075 #LATIN SMALL LETTER U */
{ "\x76",1 },	/* 76  0076 #LATIN SMALL LETTER V */
{ "\x77",1 },	/* 77  0077 #LATIN SMALL LETTER W */
{ "\x78",1 },	/* 78  0078 #LATIN SMALL LETTER X */
{ "\x79",1 },	/* 79  0079 #LATIN SMALL LETTER Y */
{ "\x7a",1 },	/* 7A  007A #LATIN SMALL LETTER Z */
{ "\x7b",1 },	/* 7B  007B #LEFT CURLY BRACKET */
{ "\x7c",1 },	/* 7C  007C #VERTICAL LINE */
{ "\x7d",1 },	/* 7D  007D #RIGHT CURLY BRACKET */
{ "\x7e",1 },	/* 7E  007E #TILDE */
{ "\x7f",1 },	/* 7F  007F #DELETE */
{ "\xe2\x82\xac", 3 },	/* 80  20AC #EURO SIGN */
{ "\xef\xbf\xbd", 3 },	/* 81       #UNDEFINED */
{ "\xe2\x80\x9a", 3 },	/* 82  201A #SINGLE LOW-9 QUOTATION MARK */
{ "\xc6\x92" ,2 },	/* 83  0192 #LATIN SMALL LETTER F WITH HOOK */
{ "\xe2\x80\x9e", 3 },	/* 84  201E #DOUBLE LOW-9 QUOTATION MARK */
{ "\xe2\x80\xa6", 3 },	/* 85  2026 #HORIZONTAL ELLIPSIS */
{ "\xe2\x80\xa0", 3 },	/* 86  2020 #DAGGER */
{ "\xe2\x80\xa1", 3 },	/* 87  2021 #DOUBLE DAGGER */
{ "\xcb\x86" ,2 },	/* 88  02C6 #MODIFIER LETTER CIRCUMFLEX ACCENT */
{ "\xe2\x80\xb0", 3 },	/* 89  2030 #PER MILLE SIGN */
{ "\xc5\xa0" ,2 },	/* 8A  0160 #LATIN CAPITAL LETTER S WITH CARON */
{ "\xe2\x80\xb9", 3 },	/* 8B  2039 #SINGLE LEFT-POINTING ANGLE QUOTATION MARK */
{ "\xc5\x92" ,2 },	/* 8C  0152 #LATIN CAPITAL LIGATURE OE */
{ "\xef\xbf\xbd", 3 },	/* 8D       #UNDEFINED */
{ "\xc5\xbd" ,2 },	/* 8E  017D #LATIN CAPITAL LETTER Z WITH CARON */
{ "\xef\xbf\xbd", 3 },	/* 8F       #UNDEFINED */
{ "\xef\xbf\xbd", 3 },	/* 90       #UNDEFINED */
{ "\xe2\x80\x98", 3 },	/* 91  2018 #LEFT SINGLE QUOTATION MARK */
{ "\xe2\x80\x99", 3 },	/* 92  2019 #RIGHT SINGLE QUOTATION MARK */
{ "\xe2\x80\x9c", 3 },	/* 93  201C #LEFT DOUBLE QUOTATION MARK */
{ "\xe2\x80\x9d", 3 },	/* 94  201D #RIGHT DOUBLE QUOTATION MARK */
{ "\xe2\x80\xa2", 3 },	/* 95  2022 #BULLET */
{ "\xe2\x80\x93", 3 },	/* 96  2013 #EN DASH */
{ "\xe2\x80\x94", 3 },	/* 97  2014 #EM DASH */
{ "\xcb\x9c" ,2 },	/* 98  02DC #SMALL TILDE */
{ "\xe2\x84\xa2", 3 },	/* 99  2122 #TRADE MARK SIGN */
{ "\xc5\xa1" ,2 },	/* 9A  0161 #LATIN SMALL LETTER S WITH CARON */
{ "\xe2\x80\xba", 3 },	/* 9B  203A #SINGLE RIGHT-POINTING ANGLE QUOTATION MARK */
{ "\xc5\x93" ,2 },	/* 9C  0153 #LATIN SMALL LIGATURE OE */
{ "\xef\xbf\xbd", 3 },	/* 9D       #UNDEFINED */
{ "\xc5\xbe" ,2 },	/* 9E  017E #LATIN SMALL LETTER Z WITH CARON */
{ "\xc5\xb8" ,2 },	/* 9F  0178 #LATIN CAPITAL LETTER Y WITH DIAERESIS */
{ "\xc2\xa0" ,2 },	/* A0  00A0 #NO-BREAK SPACE */
{ "\xc2\xa1" ,2 },	/* A1  00A1 #INVERTED EXCLAMATION MARK */
{ "\xc2\xa2" ,2 },	/* A2  00A2 #CENT SIGN */
{ "\xc2\xa3" ,2 },	/* A3  00A3 #POUND SIGN */
{ "\xc2\xa4" ,2 },	/* A4  00A4 #CURRENCY SIGN */
{ "\xc2\xa5" ,2 },	/* A5  00A5 #YEN SIGN */
{ "\xc2\xa6" ,2 },	/* A6  00A6 #BROKEN BAR */
{ "\xc2\xa7" ,2 },	/* A7  00A7 #SECTION SIGN */
{ "\xc2\xa8" ,2 },	/* A8  00A8 #DIAERESIS */
{ "\xc2\xa9" ,2 },	/* A9  00A9 #COPYRIGHT SIGN */
{ "\xc2\xaa" ,2 },	/* AA  00AA #FEMININE ORDINAL INDICATOR */
{ "\xc2\xab" ,2 },	/* AB  00AB #LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
{ "\xc2\xac" ,2 },	/* AC  00AC #NOT SIGN */
{ "\xc2\xad" ,2 },	/* AD  00AD #SOFT HYPHEN */
{ "\xc2\xae" ,2 },	/* AE  00AE #REGISTERED SIGN */
{ "\xc2\xaf" ,2 },	/* AF  00AF #MACRON */
{ "\xc2\xb0" ,2 },	/* B0  00B0 #DEGREE SIGN */
{ "\xc2\xb1" ,2 },	/* B1  00B1 #PLUS-MINUS SIGN */
{ "\xc2\xb2" ,2 },	/* B2  00B2 #SUPERSCRIPT TWO */
{ "\xc2\xb3" ,2 },	/* B3  00B3 #SUPERSCRIPT THREE */
{ "\xc2\xb4" ,2 },	/* B4  00B4 #ACUTE ACCENT */
{ "\xc2\xb5" ,2 },	/* B5  00B5 #MICRO SIGN */
{ "\xc2\xb6" ,2 },	/* B6  00B6 #PILCROW SIGN */
{ "\xc2\xb7" ,2 },	/* B7  00B7 #MIDDLE DOT */
{ "\xc2\xb8" ,2 },	/* B8  00B8 #CEDILLA */
{ "\xc2\xb9" ,2 },	/* B9  00B9 #SUPERSCRIPT ONE */
{ "\xc2\xba" ,2 },	/* BA  00BA #MASCULINE ORDINAL INDICATOR */
{ "\xc2\xbb" ,2 },	/* BB  00BB #RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
{ "\xc2\xbc" ,2 },	/* BC  00BC #VULGAR FRACTION ONE QUARTER */
{ "\xc2\xbd" ,2 },	/* BD  00BD #VULGAR FRACTION ONE HALF */
{ "\xc2\xbe" ,2 },	/* BE  00BE #VULGAR FRACTION THREE QUARTERS */
{ "\xc2\xbf" ,2 },	/* BF  00BF #INVERTED QUESTION MARK */
{ "\xc3\x80" ,2 },	/* C0  00C0 #LATIN CAPITAL LETTER A WITH GRAVE */
{ "\xc3\x81" ,2 },	/* C1  00C1 #LATIN CAPITAL LETTER A WITH ACUTE */
{ "\xc3\x82" ,2 },	/* C2  00C2 #LATIN CAPITAL LETTER A WITH CIRCUMFLEX */
{ "\xc3\x83" ,2 },	/* C3  00C3 #LATIN CAPITAL LETTER A WITH TILDE */
{ "\xc3\x84" ,2 },	/* C4  00C4 #LATIN CAPITAL LETTER A WITH DIAERESIS */
{ "\xc3\x85" ,2 },	/* C5  00C5 #LATIN CAPITAL LETTER A WITH RING ABOVE */
{ "\xc3\x86" ,2 },	/* C6  00C6 #LATIN CAPITAL LETTER AE */
{ "\xc3\x87" ,2 },	/* C7  00C7 #LATIN CAPITAL LETTER C WITH CEDILLA */
{ "\xc3\x88" ,2 },	/* C8  00C8 #LATIN CAPITAL LETTER E WITH GRAVE */
{ "\xc3\x89" ,2 },	/* C9  00C9 #LATIN CAPITAL LETTER E WITH ACUTE */
{ "\xc3\x8a" ,2 },	/* CA  00CA #LATIN CAPITAL LETTER E WITH CIRCUMFLEX */
{ "\xc3\x8b" ,2 },	/* CB  00CB #LATIN CAPITAL LETTER E WITH DIAERESIS */
{ "\xc3\x8c" ,2 },	/* CC  00CC #LATIN CAPITAL LETTER I WITH GRAVE */
{ "\xc3\x8d" ,2 },	/* CD  00CD #LATIN CAPITAL LETTER I WITH ACUTE */
{ "\xc3\x8e" ,2 },	/* CE  00CE #LATIN CAPITAL LETTER I WITH CIRCUMFLEX */
{ "\xc3\x8f" ,2 },	/* CF  00CF #LATIN CAPITAL LETTER I WITH DIAERESIS */
{ "\xc3\x90" ,2 },	/* D0  00D0 #LATIN CAPITAL LETTER ETH */
{ "\xc3\x91" ,2 },	/* D1  00D1 #LATIN CAPITAL LETTER N WITH TILDE */
{ "\xc3\x92" ,2 },	/* D2  00D2 #LATIN CAPITAL LETTER O WITH GRAVE */
{ "\xc3\x93" ,2 },	/* D3  00D3 #LATIN CAPITAL LETTER O WITH ACUTE */
{ "\xc3\x94" ,2 },	/* D4  00D4 #LATIN CAPITAL LETTER O WITH CIRCUMFLEX */
{ "\xc3\x95" ,2 },	/* D5  00D5 #LATIN CAPITAL LETTER O WITH TILDE */
{ "\xc3\x96" ,2 },	/* D6  00D6 #LATIN CAPITAL LETTER O WITH DIAERESIS */
{ "\xc3\x97" ,2 },	/* D7  00D7 #MULTIPLICATION SIGN */
{ "\xc3\x98" ,2 },	/* D8  00D8 #LATIN CAPITAL LETTER O WITH STROKE */
{ "\xc3\x99" ,2 },	/* D9  00D9 #LATIN CAPITAL LETTER U WITH GRAVE */
{ "\xc3\x9a" ,2 },	/* DA  00DA #LATIN CAPITAL LETTER U WITH ACUTE */
{ "\xc3\x9b" ,2 },	/* DB  00DB #LATIN CAPITAL LETTER U WITH CIRCUMFLEX */
{ "\xc3\x9c" ,2 },	/* DC  00DC #LATIN CAPITAL LETTER U WITH DIAERESIS */
{ "\xc3\x9d" ,2 },	/* DD  00DD #LATIN CAPITAL LETTER Y WITH ACUTE */
{ "\xc3\x9e" ,2 },	/* DE  00DE #LATIN CAPITAL LETTER THORN */
{ "\xc3\x9f" ,2 },	/* DF  00DF #LATIN SMALL LETTER SHARP S */
{ "\xc3\xa0" ,2 },	/* E0  00E0 #LATIN SMALL LETTER A WITH GRAVE */
{ "\xc3\xa1" ,2 },	/* E1  00E1 #LATIN SMALL LETTER A WITH ACUTE */
{ "\xc3\xa2" ,2 },	/* E2  00E2 #LATIN SMALL LETTER A WITH CIRCUMFLEX */
{ "\xc3\xa3" ,2 },	/* E3  00E3 #LATIN SMALL LETTER A WITH TILDE */
{ "\xc3\xa4" ,2 },	/* E4  00E4 #LATIN SMALL LETTER A WITH DIAERESIS */
{ "\xc3\xa5" ,2 },	/* E5  00E5 #LATIN SMALL LETTER A WITH RING ABOVE */
{ "\xc3\xa6" ,2 },	/* E6  00E6 #LATIN SMALL LETTER AE */
{ "\xc3\xa7" ,2 },	/* E7  00E7 #LATIN SMALL LETTER C WITH CEDILLA */
{ "\xc3\xa8" ,2 },	/* E8  00E8 #LATIN SMALL LETTER E WITH GRAVE */
{ "\xc3\xa9" ,2 },	/* E9  00E9 #LATIN SMALL LETTER E WITH ACUTE */
{ "\xc3\xaa" ,2 },	/* EA  00EA #LATIN SMALL LETTER E WITH CIRCUMFLEX */
{ "\xc3\xab" ,2 },	/* EB  00EB #LATIN SMALL LETTER E WITH DIAERESIS */
{ "\xc3\xac" ,2 },	/* EC  00EC #LATIN SMALL LETTER I WITH GRAVE */
{ "\xc3\xad" ,2 },	/* ED  00ED #LATIN SMALL LETTER I WITH ACUTE */
{ "\xc3\xae" ,2 },	/* EE  00EE #LATIN SMALL LETTER I WITH CIRCUMFLEX */
{ "\xc3\xaf" ,2 },	/* EF  00EF #LATIN SMALL LETTER I WITH DIAERESIS */
{ "\xc3\xb0" ,2 },	/* F0  00F0 #LATIN SMALL LETTER ETH */
{ "\xc3\xb1" ,2 },	/* F1  00F1 #LATIN SMALL LETTER N WITH TILDE */
{ "\xc3\xb2" ,2 },	/* F2  00F2 #LATIN SMALL LETTER O WITH GRAVE */
{ "\xc3\xb3" ,2 },	/* F3  00F3 #LATIN SMALL LETTER O WITH ACUTE */
{ "\xc3\xb4" ,2 },	/* F4  00F4 #LATIN SMALL LETTER O WITH CIRCUMFLEX */
{ "\xc3\xb5" ,2 },	/* F5  00F5 #LATIN SMALL LETTER O WITH TILDE */
{ "\xc3\xb6" ,2 },	/* F6  00F6 #LATIN SMALL LETTER O WITH DIAERESIS */
{ "\xc3\xb7" ,2 },	/* F7  00F7 #DIVISION SIGN */
{ "\xc3\xb8" ,2 },	/* F8  00F8 #LATIN SMALL LETTER O WITH STROKE */
{ "\xc3\xb9" ,2 },	/* F9  00F9 #LATIN SMALL LETTER U WITH GRAVE */
{ "\xc3\xba" ,2 },	/* FA  00FA #LATIN SMALL LETTER U WITH ACUTE */
{ "\xc3\xbb" ,2 },	/* FB  00FB #LATIN SMALL LETTER U WITH CIRCUMFLEX */
{ "\xc3\xbc" ,2 },	/* FC  00FC #LATIN SMALL LETTER U WITH DIAERESIS */
{ "\xc3\xbd" ,2 },	/* FD  00FD #LATIN SMALL LETTER Y WITH ACUTE */
{ "\xc3\xbe" ,2 },	/* FE  00FE #LATIN SMALL LETTER THORN */
{ "\xc3\xbf" ,2 },	/* FF  00FF #LATIN SMALL LETTER Y WITH DIAERESIS */
 };
